
let student = [
    {
        roll                   : 1,
        name                   : 'Asrful haqe',
        age                    : 30,
        location               : 'Mirpur',
        skill                  : 'MERN',
        income                 : 3000,
    },
    {
        roll                   : 2,
        name                   : 'Joy Sarker',
        age                    : 30,
        location               : 'Mirpur',
        skill                  : 'MERN',
        income                 :1000,
    },
    {
        roll                   : 3,
        name                   : 'Zahdul islam',
        age                    : 33,
        location               : 'Banani',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
    {
        roll                   : 4,
        name                   : 'Malak akanda',
        age                    : 33,
        location               : 'Banani',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
    {
        roll                   : 5,
        name                   : 'Zahdul islam',
        age                    : 33,
        location               : 'Banani',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
    {
        roll                   : 6,
        name                   : 'Arif islam',
        age                    : 33,
        location               : 'Mirpur',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
    {
        roll                   : 7,
        name                   : 'Hamidul islam',
        age                    : 33,
        location               : 'Banani',
        skill                  : 'Mirpur',
        income                 : 3000,
    },
    {
        roll                   : 8,
        name                   : 'Awra islam',
        age                    : 33,
        location               : 'Gazipur',
        skill                  : 'Javascript',
        income                 : 8000,
    },
    {
        roll                   : 9,
        name                   : 'Problem islam',
        age                    : 33,
        location               : 'Gazipur',
        skill                  : 'Javascript',
        income                 : 3000,
    },
    {
        roll                   : 10,
        name                   : 'Indo Madam',
        age                    : 23,
        location               : 'Gazipur',
        skill                  : 'Payton',
        income                 : 1000,
    },
    {
        roll                   : 11,
        name                   : 'Abishik bacchan',
        age                    : 33,
        location               : 'Joydebpur',
        skill                  : 'Payton',
        income                 : 2000,
    },
    {
        roll                   : 12,
        name                   : 'Feeling islam',
        age                    : 33,
        location               : 'Joydebpur',
        skill                  : 'PHP',
        income                 : 3000,
    },
    {
        roll                   : 13,
        name                   : 'Hmaidul Islam',
        age                    : 33,
        location               : 'Mhammadpur',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
    {
        roll                   : 14,
        name                   : 'Jillur Rhaman',
        age                    : 33,
        location               : 'Baridara',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
    {
        roll                   : 15,
        name                   : 'Ariful islam',
        age                    : 33,
        location               : 'Baridara',
        skill                  : 'Java',
        income                 : 3000,
    },
    {
        roll                   : 16,
        name                   : 'Janntul-Fardus',
        age                    : 33,
        location               : 'Gulshan',
        skill                  : 'Java',
        income                 : 3000,
    },
    {
        roll                   : 17,
        name                   : 'Pream Isam',
        age                    : 33,
        location               : 'Gulshan',
        skill                  : 'Java',
        income                 : 3000,
    },
    {
        roll                   : 18,
        name                   : 'Kumar Islam',
        age                    : 33,
        location               : 'Gulshan',
        skill                  : 'Java',
        income                 : 3000,
    },
    {
        roll                   : 19,
        name                   : 'Jeet ',
        age                    : 33,
        location               : 'Uttara',
        skill                  : 'Laraval',
        income                 : 3000,
    },
    {
        roll                   : 20,
        name                   : 'Dev',
        age                    : 33,
        location               : 'Uttara',
        skill                  : 'Laraval',
        income                 : 3000,
    },
    {
        roll                   : 21,
        name                   : 'Shough Islam',
        age                    : 33,
        location               : 'Abdullapur',
        skill                  : 'Jango',
        income                 : 3000,
    },
    {
        roll                   : 22,
        name                   : 'Shofukul Islam',
        age                    : 33,
        location               : 'Abdullapur',
        skill                  : 'Jango',
        income                 : 3000,
    },
    {
        roll                   : 23,
        name                   : 'Kolpona Rani',
        age                    : 33,
        location               : 'Tongi',
        skill                  : 'Go lang',
        income                 : 3000,
    },
    {
        roll                   : 24,
        name                   : 'Abir Islam',
        age                    : 33,
        location               : 'Tongi',
        skill                  : 'Go lang',
        income                 : 3000,
    },
    {
        roll                   : 25,
        name                   : 'Plash Das',
        age                    : 33,
        location               : 'Tongi',
        skill                  : 'Golang',
        income                 : 3000,
    },    {
        roll                   : 26,
        name                   : 'Gomber Islam',
        age                    : 33,
        location               : 'Syhlet',
        skill                  : 'Java',
        income                 : 3000,
    },
    {
        roll                   : 27,
        name                   : 'Protaiba Islam',
        age                    : 33,
        location               : 'Syhlet',
        skill                  : 'Javascript',
        income                 : 3000,
    },
    {
        roll                   : 28,
        name                   : 'Tapur Rani',
        age                    : 33,
        location               : 'Sunamganj',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
    {
        roll                   : 29,
        name                   : 'Muskil Isam',
        age                    : 33,
        location               : 'Sumnamganj',
        skill                  : 'Wordpress',
        income                 : 3000,
    },
];